### ISSUE TITLE
Create ME report for the ITD course

### ISSUE THREAD

**Issue by caromelendezl** [CodeYourFuture/glasgow-volunteeer-planning#32]
To Create an Monitoring and Evaluation Report for the Intro To Digital Course.

To provide transparent data and basis to analyze the performance of the course and its real impact on the ground. This will help with evidence-based decisions and assist us to make informed decisions on the ITD course for the next cohort.

Tandy Nicole [4 Oct at 23:28]
I am going to put this ticket on the block.
Although I would like to create a ME Report, i am not sure if this will be used for future improvements. If not there is no need for me to create it.

Irina Preda [11 Aug at 18:24]
@tandynicole are there any updates? let us know if you need help with it!

**Comment by caromelendezl** [comment]
@SallyMcGrath do you need we need this card? I was thinking of closing this and putting it in the archive column as this was discussed in the old Trello Kanban and not sure if this needs to be discussed for the next cohort?

**Comment by SallyMcGrath** [comment]
Never heard of this project.
